services:
  frontend:
    build:
      context: .
      dockerfile: apps/frontend/Dockerfile
    ports:
      - "127.0.0.1:5173:5173"

  backend:
    build:
      context: .
      dockerfile: apps/backend/Dockerfile
    ports:
      - "127.0.0.1:3000:3000"

  db:
    image: postgres:18-alpine
    environment:
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
