create extension if not exists "moddatetime" with schema "extensions";


  create table "public"."announcement" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone default now(),
    "updated_at" timestamp with time zone,
    "author_uid" uuid not null,
    "title" text not null,
    "content" text not null,
    "expiry" timestamp with time zone
      );


alter table "public"."announcement" enable row level security;

CREATE UNIQUE INDEX announcement_pkey ON public.announcement USING btree (id);

alter table "public"."announcement" add constraint "announcement_pkey" PRIMARY KEY using index "announcement_pkey";

alter table "public"."announcement" add constraint "announcement_author_uid_fkey" FOREIGN KEY (author_uid) REFERENCES auth.users(id) not valid;

alter table "public"."announcement" validate constraint "announcement_author_uid_fkey";

grant delete on table "public"."announcement" to "anon";

grant insert on table "public"."announcement" to "anon";

grant references on table "public"."announcement" to "anon";

grant select on table "public"."announcement" to "anon";

grant trigger on table "public"."announcement" to "anon";

grant truncate on table "public"."announcement" to "anon";

grant update on table "public"."announcement" to "anon";

grant delete on table "public"."announcement" to "authenticated";

grant insert on table "public"."announcement" to "authenticated";

grant references on table "public"."announcement" to "authenticated";

grant select on table "public"."announcement" to "authenticated";

grant trigger on table "public"."announcement" to "authenticated";

grant truncate on table "public"."announcement" to "authenticated";

grant update on table "public"."announcement" to "authenticated";

grant delete on table "public"."announcement" to "service_role";

grant insert on table "public"."announcement" to "service_role";

grant references on table "public"."announcement" to "service_role";

grant select on table "public"."announcement" to "service_role";

grant trigger on table "public"."announcement" to "service_role";

grant truncate on table "public"."announcement" to "service_role";

grant update on table "public"."announcement" to "service_role";


  create policy "Enable insert for users based on user_id"
  on "public"."announcement"
  as permissive
  for insert
  to public
with check ((( SELECT auth.uid() AS uid) = author_uid));



  create policy "Enable read access for all users"
  on "public"."announcement"
  as permissive
  for select
  to authenticated
using (true);


CREATE TRIGGER handle_updated_at BEFORE UPDATE ON public.announcement FOR EACH ROW EXECUTE FUNCTION extensions.moddatetime('updated_at');


